### PR TITLE
Fix additional item types

### PR DESCRIPTION
**Pull request by cyhyraethz**
Quarter Staff -> Quarterstaff

Bec-De-Corbin -> Bec-de-Corbin

### CODE REVIEW

**Comment by Nasicus** [comment]
Are you sure about Bec-de-Cobin => accoridng to: https://diablo.fandom.com/wiki/Bec-De-Corbin  it's correct

**Comment by cyhyraethz** [comment]
It looks like Bec-de-Corbin to me, like Martel de Fer.

Screenshot from 2021-09-23 11-28-21

Screenshot from 2021-09-23 11-32-37

You're right that on websites like the Arreat Summit it's listed as Bec-De-Corbin though (http://classic.battle.net/diablo2exp/items/exceptional/polearms.shtml).

**Comment by Nasicus** [comment]
Think it's uppercase (even in game, I think the font sucks :D) - so revert this one please :()

**Comment by cyhyraethz** [comment]
It's definitely Bec-de-Corbin in-game. I just checked the game files and it's Bec-de-Corbin in Weapons.txt. I can still revert it if you want though.

Screenshot from 2021-09-23 12-19-44

**Comment by cyhyraethz** [comment]
Here's how it looks in-game without any mods or changes:
Screenshot from 2021-09-23 13-27-02

Here's how it looks when I force it to display as Bec-de-Corbin using my loot filter:
Screenshot from 2021-09-23 13-40-05

Here's how it looks when I force it to display as Bec-De-Corbin using my loot filter:
Screenshot from 2021-09-23 13-36-17

**Comment by Nasicus** [comment]
Thanks for all the works for this small thing :D I don't have a strong feeling anyway, but if it's even correct ihe games own files I have no problem with mergin this 👍

**Pull request merged**
